/**
 * @fileoverview ChartInsight — a compact "AI read" footer for any chart card.
 *
 * Reuses the dashboard AI-insight visual treatment (Sparkles badge, chart-1
 * accent, "Generated by Workers AI") and calls POST /api/ai/chart-insight with
 * the chart's already-aggregated rows to render a one-paragraph reading plus
 * any flagged anomalies. Lazy: it fetches once the chart has data, and can be
 * regenerated.
 */

"use client";

import { AlertTriangle, RefreshCw, Sparkles } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { apiSend } from "@/lib/api";

import type { ChartInsightResponse } from "./types";

export interface ChartInsightProps {
  /** Chart title — included in the prompt for grounding. */
  title: string;
  /** Optional chart description (e.g. the SQL source). */
  description?: string;
  /** The chart's aggregated rows. When empty, the insight stays idle. */
  rows: Record<string, unknown>[];
}

/**
 * AI interpretation + anomaly footer for a chart. Auto-loads when `rows`
 * first becomes non-empty; a refresh button re-runs the model.
 */
export function ChartInsight({ title, description, rows }: ChartInsightProps) {
  const [data, setData] = useState<ChartInsightResponse | null>(null);
  const [loading, setLoading] = useState(false);
  // Guard so we only auto-fetch once per distinct dataset signature.
  const lastSig = useRef<string>("");

  const run = useCallback(async () => {
    if (!rows.length) return;
    setLoading(true);
    try {
      setData(await apiSend<ChartInsightResponse>("POST", "ai/chart-insight", { title, description, rows }));
    } catch (err) {
      setData({ ok: false, error: err instanceof Error ? err.message : String(err) });
    } finally {
      setLoading(false);
    }
  }, [rows, title, description]);

  useEffect(() => {
    const sig = `${rows.length}:${JSON.stringify(rows[0] ?? {})}`;
    if (rows.length && sig !== lastSig.current) {
      lastSig.current = sig;
      void run();
    }
  }, [rows, run]);

  if (!rows.length) return null;

  return (
    <div className="mt-3 rounded-md bg-gradient-to-br from-muted/30 to-transparent p-3 ring-1 ring-border/40">
      <div className="mb-1.5 flex items-center justify-between gap-2">
        <Badge variant="secondary" className="gap-1.5" style={{ color: "var(--chart-2)" }}>
          <Sparkles className="size-3" aria-hidden />
          AI read
        </Badge>
        <Button
          size="icon"
          variant="ghost"
          className="size-6"
          onClick={() => void run()}
          disabled={loading}
          aria-label="Regenerate AI read"
        >
          <RefreshCw className={loading ? "size-3 animate-spin" : "size-3"} />
        </Button>
      </div>

      {loading && !data ? (
        <div className="flex flex-col gap-1.5" aria-busy>
          <Skeleton className="h-3 w-[92%]" />
          <Skeleton className="h-3 w-[70%]" />
        </div>
      ) : null}

      {data?.ok ? (
        <div className="flex flex-col gap-2">
          {data.reading ? (
            <p className="text-xs leading-relaxed text-foreground/90">{data.reading}</p>
          ) : null}
          {data.anomalies && data.anomalies.length > 0 ? (
            <ul className="flex flex-col gap-1">
              {data.anomalies.map((a, i) => (
                <li key={i} className="flex items-start gap-1.5 text-xs text-foreground/80">
                  <AlertTriangle className="mt-0.5 size-3 shrink-0" style={{ color: "var(--chart-4)" }} aria-hidden />
                  <span>{a}</span>
                </li>
              ))}
            </ul>
          ) : null}
        </div>
      ) : null}

      {data && !data.ok ? (
        <p className="text-xs text-destructive">{data.error ?? "AI read unavailable."}</p>
      ) : null}
    </div>
  );
}
