/**
 * @fileoverview AI Insights panel — the headline feature of the dashboard.
 *
 * Calls `GET /api/dashboard/insights` (Workers AI) and renders the returned
 * markdown-ish bullet string. The backend guarantees a "- " prefixed bullet
 * list, so we parse leading "- " / "* " markers into a styled list and fall
 * back to paragraph rendering for any other shape. A lightweight inline parser
 * also honours `**bold**` and `` `code` `` spans — enough for the analyst
 * output without pulling in a markdown dependency.
 *
 * Visual treatment is deliberately prominent: a gradient-accented `bg-card`
 * surface with a "Generated by Workers AI" badge, a refresh button, the
 * generated-at relative time, and a shimmering "thinking" skeleton while the
 * model streams.
 */

"use client";

import { RefreshCw, Sparkles } from "lucide-react";
import { Fragment } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { relativeTime } from "@/lib/format";

import { InlineError } from "./shared";
import type { DashboardInsights } from "./types";
import type { Resource } from "./useDashboardData";

/**
 * Split the insight string into discrete bullet lines. Lines beginning with
 * `-` or `*` (optionally indented) are treated as bullets; everything else is
 * kept as a paragraph line.
 */
function parseLines(insight: string): { bullet: boolean; text: string }[] {
  return insight
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => {
      const m = /^[-*]\s+(.*)$/.exec(l);
      return m ? { bullet: true, text: m[1] } : { bullet: false, text: l };
    });
}

/**
 * Render inline `**bold**` and `` `code` `` spans inside a single line without
 * a markdown library. Returns an array of React nodes.
 */
function renderInline(text: string): React.ReactNode[] {
  const parts = text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).filter(Boolean);
  return parts.map((part, i) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return (
        <strong key={i} className="font-semibold text-foreground">
          {part.slice(2, -2)}
        </strong>
      );
    }
    if (part.startsWith("`") && part.endsWith("`")) {
      return (
        <code
          key={i}
          className="rounded bg-muted px-1 py-0.5 font-mono text-[0.85em] text-foreground"
        >
          {part.slice(1, -1)}
        </code>
      );
    }
    return <Fragment key={i}>{part}</Fragment>;
  });
}

export function InsightsPanel({
  resource,
}: {
  resource: Resource<DashboardInsights>;
}) {
  const { data, loading, error, reload } = resource;
  const lines = data ? parseLines(data.insight) : [];
  const bullets = lines.filter((l) => l.bullet);
  const paragraphs = lines.filter((l) => !l.bullet);

  return (
    <Card className="overflow-hidden bg-gradient-to-br from-card to-card ring-1 ring-border/40">
      {/* Accent strip drawn from the chart palette for a "headline" feel. */}
      <div
        className="h-1 w-full"
        style={{
          background:
            "linear-gradient(90deg, var(--chart-1), var(--chart-2), var(--chart-5))",
        }}
        aria-hidden
      />
      <CardHeader>
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="flex items-start gap-3">
            <span
              className="mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-md ring-1 ring-border/40"
              style={{ backgroundColor: "color-mix(in oklch, var(--chart-1) 16%, transparent)" }}
            >
              <Sparkles className="size-4.5" style={{ color: "var(--chart-1)" }} aria-hidden />
            </span>
            <div>
              <CardTitle className="text-lg">AI Insights</CardTitle>
              <CardDescription>
                Trends, risks, and recommendations synthesized from your live data.
              </CardDescription>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Badge
              variant="secondary"
              className="gap-1.5 whitespace-nowrap"
              style={{ color: "var(--chart-2)" }}
            >
              <Sparkles className="size-3" aria-hidden />
              Generated by Workers AI
            </Badge>
            <Button
              size="icon"
              variant="outline"
              onClick={reload}
              disabled={loading}
              aria-label="Regenerate insights"
            >
              <RefreshCw className={loading ? "size-4 animate-spin" : "size-4"} />
            </Button>
          </div>
        </div>
      </CardHeader>

      <CardContent className="flex flex-col gap-4">
        {error ? <InlineError message={error} onRetry={reload} /> : null}

        {loading && !data ? (
          <div className="flex flex-col gap-3" aria-busy>
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Sparkles className="size-4 animate-pulse" style={{ color: "var(--chart-1)" }} />
              Thinking…
            </div>
            <Skeleton className="h-4 w-[90%]" />
            <Skeleton className="h-4 w-[78%]" />
            <Skeleton className="h-4 w-[85%]" />
            <Skeleton className="h-4 w-[60%]" />
          </div>
        ) : null}

        {data && !error ? (
          <>
            {bullets.length > 0 ? (
              <ul className="flex flex-col gap-3">
                {bullets.map((b, i) => (
                  <li key={i} className="flex gap-3">
                    <span
                      className="mt-2 size-1.5 shrink-0 rounded-full"
                      style={{ backgroundColor: "var(--chart-1)" }}
                      aria-hidden
                    />
                    <span className="text-sm leading-relaxed text-foreground/90">
                      {renderInline(b.text)}
                    </span>
                  </li>
                ))}
              </ul>
            ) : null}

            {paragraphs.length > 0 ? (
              <div className="flex flex-col gap-2">
                {paragraphs.map((p, i) => (
                  <p key={i} className="text-sm leading-relaxed text-foreground/90">
                    {renderInline(p.text)}
                  </p>
                ))}
              </div>
            ) : null}

            <p className="text-xs text-muted-foreground">
              Updated {relativeTime(data.generatedAt)}
            </p>
          </>
        ) : null}
      </CardContent>
    </Card>
  );
}
